package atux.vistas.reportes;

//import atux.controllers.CFactores;
import atux.modelgui.ModeloTablaExportarConCad;
import atux.modelgui.ModeloTablaLocales;
import atux.util.Helper;
import atux.util.common.AtuxVariables;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import com.toedter.calendar.JDateChooser;
import java.io.File;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
/**
 *
 * @author Cesar Ruiz  PC
 */
public class IExportaConCad extends javax.swing.JInternalFrame {
//    private CFactores cp;
    private ModeloTablaExportarConCad mtp;
    private boolean esActualizacion = false;
    private int tipoSeleccion = -1; //-1 todo,1 activos, 0 No activos
    public int finalPag = 0;//cont
    public int tmpFp = finalPag;
    public int inicioPag = 0;
    public int numRegistros = 0;
    private final Log logger = LogFactory.getLog(getClass()); 
    /** Creates new form IImpuestoIGV */
    
    public IExportaConCad() {
        initComponents();
        Limpiar();
        dteFechaInicio.requestFocus();

        CargaDatos();
        tblListado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
//        Helper.ajustarSoloAnchoColumnas(tblListado, ModeloTablaLocales.anchoColumnas);
//        Helper.ajustarAnchoColumnas(tblListado);
//        setEventSelectionModel(tblListado.getSelectionModel());


//        cp = new CExportarConCad();
//        mtp = new ModeloTablaExportarConCad(inicioPag,finalPag);
//        numRegistros = mtp.getCantidadRegistros();
//        setEventSelectionModel(tblListado.getSelectionModel());

    }

    private void setEventSelectionModel(ListSelectionModel lsm){
        ListSelectionListener lsl = new ListSelectionListener(){
//            @Override
            public void valueChanged(ListSelectionEvent e) {
                selectionEvent(e);
            }
        };
        lsm.addListSelectionListener(lsl);
    }
    
    private void selectionEvent(ListSelectionEvent e){
        if(tblListado.getSelectedRow() != -1){
            numRegistros = tblListado.getSelectedRow();
//            cp.setFactoresPrecio(mtp.getFila(tblListado.getSelectedRow()));
       }
    }
    
    
    private void Limpiar(){
        this.dteFechaInicio.setDate(null);
        this.dteFechaFinal.setDate(null);
    }

    private String FormatoFecha(JDateChooser oldFecha){
        String Fecha=null;
        try {
            String formato = oldFecha.getDateFormatString();
            Date date = oldFecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            Fecha = String.valueOf(sdf.format(date));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Elija una FECHA VALIDA ", "Error..!!", JOptionPane.ERROR_MESSAGE);
        }
//
//
//
//        Date Fecha=null;
//        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
//        String dateInString = oldFecha;
//
//        try {
//            Fecha = formatter.parse(dateInString);
//        } catch (ParseException ex) {
//            Logger.getLogger(IExportaConCad.class.getName()).log(Level.SEVERE, null, ex);
//        }
        return Fecha;
    }
   
    public final void CargaDatos(){
        if (dteFechaInicio.getDate()==null || dteFechaFinal.getDate()==null){
            mtp = new ModeloTablaExportarConCad("000","000", "01/01/2000", "01/01/2000");
        }else{
            mtp = new ModeloTablaExportarConCad(AtuxVariables.vCodigoCompania,AtuxVariables.vCodigoLocal, FormatoFecha(dteFechaInicio),FormatoFecha(dteFechaFinal));
        }

//        numRegistros = mtp.getCantidadRegistros();
        tblListado.setModel(mtp);
        Helper.ajustarSoloAnchoColumnas(tblListado,ModeloTablaExportarConCad.anchoColumnas);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelImage1 = new elaprendiz.gui.panel.PanelImage();
        pnlEntradas = new javax.swing.JPanel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        dteFechaInicio = new com.toedter.calendar.JDateChooser();
        dteFechaFinal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        pnlAccionesCategorias_G01 = new javax.swing.JPanel();
        btnComsulta = new elaprendiz.gui.button.ButtonRect();
        btnExportar = new elaprendiz.gui.button.ButtonRect();
        btnSalir = new elaprendiz.gui.button.ButtonRect();

        setBorder(null);
        setResizable(true);
        setTitle("Formulario de Factores");
        setPreferredSize(new java.awt.Dimension(681, 399));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atux/resources/fondoazulceleste.jpg"))); // NOI18N

        pnlEntradas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(0), "Datos de Factores", 1, 2));
        pnlEntradas.setOpaque(false);
        pnlEntradas.setPreferredSize(new java.awt.Dimension(748, 107));

        lblFechaInicio.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblFechaInicio.setText("Fecha Inicio");

        lblFechaFin.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblFechaFin.setText("Fecha Final");

        dteFechaInicio.setBackground(new java.awt.Color(0, 0, 0));
        dteFechaInicio.setForeground(new java.awt.Color(255, 0, 0));
        dteFechaInicio.setDate(Calendar.getInstance().getTime());
        dteFechaInicio.setFont(new java.awt.Font("Tahoma", 1, 13));
        dteFechaInicio.setPreferredSize(new java.awt.Dimension(120, 22));
        dteFechaInicio.setRequestFocusEnabled(false);
        dteFechaInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dteFechaInicioKeyReleased(evt);
            }
        });

        dteFechaFinal.setBackground(new java.awt.Color(0, 0, 0));
        dteFechaFinal.setForeground(new java.awt.Color(255, 0, 0));
        dteFechaFinal.setDate(Calendar.getInstance().getTime());
        dteFechaFinal.setFont(new java.awt.Font("Tahoma", 1, 13));
        dteFechaFinal.setPreferredSize(new java.awt.Dimension(120, 22));
        dteFechaFinal.setRequestFocusEnabled(false);
        dteFechaFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dteFechaFinalKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlEntradasLayout = new javax.swing.GroupLayout(pnlEntradas);
        pnlEntradas.setLayout(pnlEntradasLayout);
        pnlEntradasLayout.setHorizontalGroup(
            pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(dteFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblFechaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEntradasLayout.setVerticalGroup(
            pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradasLayout.createSequentialGroup()
                .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFin)
                    .addComponent(dteFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaInicio))
                .addContainerGap(6, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tblListado.setColumnSelectionAllowed(true);
        tblListado.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblListado);
        tblListado.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        pnlAccionesCategorias_G01.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(0), "", 1, 2));
        pnlAccionesCategorias_G01.setOpaque(false);
        pnlAccionesCategorias_G01.setPreferredSize(new java.awt.Dimension(550, 50));

        btnComsulta.setBackground(new java.awt.Color(0, 153, 255));
        btnComsulta.setText("Consulta");
        btnComsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComsultaActionPerformed(evt);
            }
        });

        btnExportar.setBackground(new java.awt.Color(51, 153, 255));
        btnExportar.setText("Exportar");
        btnExportar.setEnabled(false);
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(51, 153, 255));
        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesCategorias_G01Layout = new javax.swing.GroupLayout(pnlAccionesCategorias_G01);
        pnlAccionesCategorias_G01.setLayout(pnlAccionesCategorias_G01Layout);
        pnlAccionesCategorias_G01Layout.setHorizontalGroup(
            pnlAccionesCategorias_G01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesCategorias_G01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnComsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlAccionesCategorias_G01Layout.setVerticalGroup(
            pnlAccionesCategorias_G01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesCategorias_G01Layout.createSequentialGroup()
                .addGroup(pnlAccionesCategorias_G01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAccionesCategorias_G01, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAccionesCategorias_G01, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Formulario Tipo de Cambio");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void dteFechaInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dteFechaInicioKeyReleased
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                dteFechaFinal.requestFocus();
                break;
        }
}//GEN-LAST:event_dteFechaInicioKeyReleased

private void dteFechaFinalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dteFechaFinalKeyReleased
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                btnComsulta.requestFocus();
                break;
        }
}//GEN-LAST:event_dteFechaFinalKeyReleased

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void btnComsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComsultaActionPerformed
    if (dteFechaInicio.getDate() ==null){
        JOptionPane.showMessageDialog(null, "Ingrese una FECHA de INCIO VALIDA", "Error..!!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (dteFechaFinal.getDate() ==null){
        JOptionPane.showMessageDialog(null, "Ingrese una FECHA FINAL VALIDA", "Error..!!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if(dteFechaFinal.getDate().before(dteFechaInicio.getDate())  ){
        JOptionPane.showMessageDialog(null, "Ingrese una FECHA FINAL no puede ser anterior a la FECHA INICIO", "Error..!!", JOptionPane.ERROR_MESSAGE);
        return;
    }

    CargaDatos();
    btnExportar.setEnabled(true);
}//GEN-LAST:event_btnComsultaActionPerformed

private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
// TODO add your handling code here:
    File archivo;
    
    
}//GEN-LAST:event_btnExportarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonRect btnComsulta;
    private elaprendiz.gui.button.ButtonRect btnExportar;
    private elaprendiz.gui.button.ButtonRect btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dteFechaFinal;
    private com.toedter.calendar.JDateChooser dteFechaInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private elaprendiz.gui.panel.PanelImage panelImage1;
    private javax.swing.JPanel pnlAccionesCategorias_G01;
    private javax.swing.JPanel pnlEntradas;
    private javax.swing.JTable tblListado;
    // End of variables declaration//GEN-END:variables
}
